spring:

  application:
    name: "tickethub-producer"

  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: "localhost"
      port: 6379



  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER_ADDRESS}



kafka:
  createTicketMessageTopic: ${KAFKA_TOPIC_NAME}

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in:
    access-token: ${JWT_EXPIRED_IN}
    refresh-token: ${REFRESH_TOKEN_EXPIRED_IN}
    ticket-token: ${TOKEN_EXPIRED_IN}
