spring:

  application:
    name: "tickethub-producer"

  datasource:
    url: ${DATASOURCE_URL_LOCAL:jdbc:mysql://localhost:3306/tickethub}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1}
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: "localhost"
      port: 6379


#
#  kafka:
#    bootstrap-servers: ${KAFKA_CLUSTER_ADDRESS:localhost:9096}
#
#
#
#kafka:
#  createTicketMessageTopic: ${KAFKA_TOPIC_NAME:name}

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in:
    access-token: ${JWT_EXPIRED_IN}
    refresh-token: ${REFRESH_TOKEN_EXPIRED_IN}
    ticket-token: ${TOKEN_EXPIRED_IN}

